[tool.black]
line-length = 80
target-version = ['py311']
include = '\.pyw?$'

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 80

[tool.pytest.ini_options]
addopts = "--cov=scripts --cov-report=html -n auto"
testpaths = ["scripts/tests"]

[tool.docformatter]
wrap-summaries = 80
wrap-descriptions = 80
pre-summary-newline = true
make-summary-multi-line = false
black = true

[tool.autoflake]
exclude = ["node_modules/*"]
remove-all-unused-imports = true
remove-unused-variables = true

[tool.autopep8]
ignore = ["E402"]
max_line_length = 80

[tool.coverage.run]
omit = ["scripts/tests/*", "scripts/__init__.py"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if __name__ == .__main__.:",
    "^\\s+main\\(\\)$",
    "^\\s+sys\\.exit\\(main\\(\\)\\)$",
    "class .*\\bProtocol\\):",
    "@(abc\\.)?abstractmethod",
    "^except ImportError:",
    "^\\s+import .*  # type: ignore$",
    "if verbose:",
]
